site_name: Duik Ángela
site_url: http://duik.rxlab.guide
repo_url: https://github.com/RxLaboratory/Duik/
edit_uri: tree/master/src-docs/docs/
site_description: The Duik User Guide
site_author: Nicolas Dufresne and contributors
copyright: 'Copyright © 2018-2023 <a href="https://rxlaboratory.org" target="_blank">Rainbox Laboratory</a> and <a href="http://duduf.com" target="_blank">Nicolas Dufresne</a>'
use_directory_urls: false
theme:
    name: null
    custom_dir: 'cinder'
    colorscheme: zenburn
extra:
    collapse_toc: true
markdown_extensions:
    - smarty
    - footnotes
    - tables
    - admonition
    - fenced_code
    - toc
    - attr_list
extra_css:
    - style.css
    - video.css
extra_javascript:
    - video.js
    - meta.js
    - collapser.js
    - video-plyr.js
site_dir: ../docs
dev_addr: '127.0.0.1:8001'
nav:
    - v17.1.x:
        - Home: index.md
        - Ángela: angela.md
        - Tutorials: tutorials.md
        - Printed User Guide: printed-user-guide.md
    - User Guide:
        - Getting Started:
            - Preamble: getting-started/preamble.md
            - Introduction to Duik: getting-started/introduction.md
            - User License: misc/license.md
            - Be Annoying!: getting-started/be-annoying.md
            - Installation: getting-started/install.md
            - First Look: getting-started/first-look.md
            - Troubleshooting: getting-started/troubleshoot.md
        - Rigging with Duik: guide/rigging.md
        - Meta-rigs and OCO: guide/oco/index.md
        - Bones and Auto-Rig:
            - Introduction: guide/bones/index.md
            - Create Bones: guide/bones/create-bones.md
            - Envelops: guide/bones/envelops.md
            - Noodles: guide/bones/noodles.md
            - Autorig:
                - Introduction: guide/bones/autorig/index.md
                - Arms and legs: guide/bones/autorig/leg.md
                - Spines: guide/bones/autorig/spine.md
                - Tails and hair: guide/bones/autorig/tail.md
                - Wings: guide/bones/autorig/wing.md
                - Fins: guide/bones/autorig/fin.md
            - Tools:
                - Select bones:  guide/bones/tools/select.md
                - Show/Hide bones:  guide/bones/tools/show-hide.md
                - Duplicate bones:  guide/bones/tools/duplicate.md
                - Link Art:  guide/bones/tools/link-art.md
                - Edit Mode:  guide/bones/tools/edit.md
                - Bake bones:  guide/bones/tools/bake.md
                - Settings:  guide/bones/tools/settings.md
        - Links & Constraints:
            - Introduction: guide/constraints/index.md
            - Connector: guide/constraints/connector.md
            - Key Morph: guide/constraints/key-morph.md
            - Pins: guide/constraints/pins.md
            - Kinematics (IK and FK): guide/constraints/kinematics.md
            - Parent constraints: guide/constraints/parent.md
            - Transform constraints: guide/constraints/transform.md
            - Tools:
                - List: guide/constraints/tools/list.md
                - Split Values: guide/constraints/tools/split.md
                - Edit Mode: guide/constraints/tools/edit-mode.md
                - Lock Property: guide/constraints/tools/lock.md
                - Zero: guide/constraints/tools/zero.md
                - Move Anchor Point: guide/constraints/tools/anchor.md
                - Expose Transform: guide/constraints/tools/etm.md
                - Locators: guide/constraints/tools/locator.md
                - Align Layers: guide/constraints/tools/align.md
                - Measure Distance: guide/constraints/tools/measure.md
                - Property Info: guide/constraints/tools/prop-info.md
        - Controllers:
                - Introduction: guide/controllers/index.md
                - Pseudo-Effects: guide/controllers/pseudo-effects.md
                - Extract Controllers: guide/controllers/extract.md
                - Tools:
                    - Select Controllers: guide/controllers/tools/select.md
                    - Show/Hide: guide/controllers/tools/show-hide.md
                    - Tag: guide/controllers/tools/tag.md
                    - Bake: guide/controllers/tools/bake.md
                    - Settings: guide/controllers/tools/settings.md
        - Automation & Expressions:
            - Introduction: guide/automation/index.md
            - Kleaner: guide/automation/kleaner.md
            - Effector: guide/automation/effector.md
            - Effector Map: guide/automation/effector-map.md
            - Wiggle: guide/automation/wiggle.md
            - Random Motion: guide/automation/random-motion.md
            - Swink: guide/automation/swink.md
            - Wheel: guide/automation/wheel.md
            - Move Away: guide/automation/move-away.md
            - Looper: guide/automation/looper.md
            - Motion Trail: guide/automation/motion-trail.md
            - Walk / Run Cycle: guide/automation/walk-run.md
            - X-Sheet: guide/automation/x-sheet.md
            - Paint Rig: guide/automation/paint-rig.md
            - Tools:
                - List: guide/automation/tools/list.md
                - Split Values: guide/automation/tools/split.md
                - Toggle Expressions: guide/automation/tools/remove-expressions.md
                - Expression Tools: guide/automation/tools/expressions-tools.md
                - Copy / Paste Expression: guide/automation/tools/copy.md
                - Edit Expression: guide/automation/tools/edit.md
                - Randomize: guide/automation/tools/randomize.md
                - Bake Expressions: guide/automation/tools/bake.md
                - Bake Composition: guide/automation/tools/bake-comp.md
                - Time Remap: guide/automation/tools/time-remap.md
        - Animation:
            - Introduction: guide/animation/index.md
            - Tweening: guide/animation/tweening.md
            - Add / Edit Keyframes: guide/animation/keyframes.md
            - Temporal interpolation: guide/animation/interpolation.md
            - Spatial interpolation: guide/animation/spatial-interpolation.md
            - Animation Library: guide/animation/anim-library.md
            - Kleaner: guide/animation/kleaner.md
            - Sequence: guide/animation/sequence.md
            - X-Sheet: guide/animation/x-sheet.md
            - Non-Linear Animation: guide/animation/nla.md
            - Cel Animation: guide/animation/cel.md
            - Tools:
                - Select Keyframes: guide/animation/tools/select.md
                - Copy / Cut / Paste: guide/animation/tools/copy.md
                - Interpolator: guide/animation/tools/interpolator.md
                - Move Anchor Points: guide/animation/tools/anchor.md
                - Align Layers: guide/animation/tools/align.md
                - Snap Keyframes: guide/animation/tools/snap.md
                - Motion Trail: guide/animation/tools/motion-trail.md
                - IK/FK Switch: guide/animation/tools/ik-fk-switch.md
        - Camera:
            - Introduction: guide/camera/index.md
            - Camera Rig: guide/camera/camera-rig.md
            - 2D Camera: guide/camera/camera-2d.md
            - Tools:
                - Framing Guides: guide/camera/tools/frame.md
                - Scale Z-Link: guide/camera/tools/scale-z-link.md
        - Tools:
            - Introduction: guide/tools/index.md
            - Composition:
                - Crop: guide/tools/composition/crop.md
                - Comp Settings (DuCop): guide/tools/composition/settings.md
            - Layer Manager: guide/tools/layers.md
            - Text:
                - Rename: guide/tools/text/rename.md
                - Search and Replace: guide/tools/text/search-replace.md
            - Scripting:
                - Script Library: guide/tools/scripting/library.md
                - Scriptify Expression: guide/tools/scripting/scriptify-expression.md
                - Script Editor: guide/tools/scripting/script-editor.md
                - Edit Expression: guide/tools/scripting/edit-expression.md
        - Command Line: guide/cmd.md
        - Notes editor: guide/notes.md
        - Sanity tests: guide/sanity.md
        - Settings: guide/settings.md
    - Advanced:
        - Performance: advanced/performance.md
        - Expressions: advanced/expressions.md
        - The Duik API:
            - Introduction: advanced/api/index.md
            - Getting Started: advanced/api/getting-started.md
            - Your First Script: advanced/api/headless-scripts.md
            - Duik Features: advanced/api/duik-features.md
            - Keyboard Shortcuts: advanced/api/shortcuts.md
            - API reference: http://duik.rxlab.io
        - Contribution: advanced/contributing-guide.md
        - Translation: http://translate-duik.rxlab.io
        - Source code: https://github.com/RxLaboratory/Duik
    - F.A.Q.: faq.md
    - ...:
        - Glossary: misc/glossary.md
        - Changelog: misc/changelog.md
        - Credits: misc/credits.md
        - Contact: http://contact.rxlab.info
        - Chat: http://chat.rxlab.info
        - Donate: http://donate.rxlab.info
        - Contribute: http://contribute.rxlab.info
        - License:
            - GNU GPLv3: misc/gnu-gpl.md
            - Documentation license: misc/doc-license.md
