site_name: Duben Documentation
site_url: https://rainboxprod.coop
repo_url: https://github.com/Rainbox-dev/DuAEF_Duik/
edit_uri: ''
site_description: Duben - Duduf Benchmark for After Effects comprehensive documentation
site_author: Nicolas Dufresne and contributors
copyright: 'Copyright © 2018 Rainbox Productions and Nicolas Dufresne'
theme: readthedocs
markdown_extensions:
    - smarty
    - footnotes
    - tables
    - admonition
    - codehilite
    - fenced_code
    - toc
plugins:
- search:
    lang: en
extra_css:
    - style.css
use_directory_urls: true
site_dir: ../../docs/Guides/Duben/
nav:
    - Duben: Duben.md
    - Guide:
        - How it works: Duben-How-to.md
        - Expressions: Duben-Expressions.md
        - Shapes: Duben-Shapes.md
        - Effects: Duben-Effects.md
        - Scripts: Duben-Script.md
        - User Interface: Duben-UI.md
        - Total: Duben-Total.md
