site_name: Duik Documentation
site_url: https://rainboxprod.coop
repo_url: https://github.com/Rainbox-dev/DuAEF_Duik/
edit_uri: edit/master/src-docs/duik/docs/
site_description: The Duik comprehensive documentation
site_author: Nicolas Dufresne and contributors
copyright: 'Copyright © 2018 Rainbox Productions and Nicolas Dufresne'
theme:
    name: readthedocs
    custom_dir: theme/
markdown_extensions:
    - smarty
    - footnotes
    - tables
    - admonition
    - codehilite
    - fenced_code
    - toc
extra_css:
    - style.css
    - video.css
extra_javascript:
    - video.js
site_dir: ../../docs/Guides/Duik/
dev_addr: '127.0.0.1:8001'
nav:
    - About: index.md
    - Bassel: bassel.md
    - Tutorials: tutorials.md
    - User Guide:
        - Introduction: duik-user-guide.md
        - Installation: install-duik.md
        - First look: first-look-at-duik.md
        - Notes editor: notes-editor.md
        - Contextual help: contextual-help.md
        - Rigging:
            - Introduction: rigging.md
            - Structures:
                - Introduction: structures.md
                - Create Structures: create-structures.md
                - Structure Tools: structure-tools.md
            - Constraints:
                - Introduction: constraints.md
                - Autorig & IK: autorig.md
                - Connector: connector.md
                - Animation Blender: animation-blender-setup.md
                - Bones: bones.md
                - Parent link: parent-link.md
                - Parent Accross Comps: parent-accross-compositions.md
                - Path Constraint: path-constraint.md
                - Position Constraint: position-constraint.md
                - Orientation Constraint: orientation-constraint.md
                - List: duik-list.md
                - Zero: zero.md
                - Lock Property: lock-property.md
            - Automations:
                - Introduction: automations.md
                - List: duik-list.md
                - Effector: effector.md
                - Wiggle: wiggle.md
                - Spring: spring.md
                - Swing: swing.md
                - Blink: blink.md
                - Wheel: wheel.md
                - Move Away: move-away.md
                - Random: random.md
                - Paint Rig: paint-rig.md
                - Walk Cycle: walk-cycle.md
                - Looper: looper.md
            - Controllers:
                - Introduction: controllers.md
                - Controller Tools: controller-tools.md
            - Tools: rigging-tools.md
        - Animation:
            - Introduction: animation.md
            - Keyframe Tools: keyframe-tools.md
            - Animation Tools:
                - Introduction: animation-tools.md
                - IK/FK Switch: ik-fk-switch.md
                - Animation Blender: animation-blender.md
                - Motion Trail: motion-trail.md
                - X-Sheet: x-sheet.md
                - Time Remapping: time-remap.md
                - Extract Controllers: controller-tools.md
                - Cel Animation: cel-animation.md
        - Camera:
            - Introduction: camera.md
            - Camera Rig: camera-rig.md
            - Scale Z-Link: scale-z-link.md
            - 2D Camera: camera-2d.md
            - Framing Guides: duframe.md
            - Import TVPaint Camera: import-tvpaint-camera.md
        - Input/Output:
            - Introduction: i-o.md
            - Import: import.md
            - Export: export.md
        - Settings: settings.md
    - F.A.Q.: duik-faq.md
    - Changelog: duik-16-changelog.md
    - Contribution: https://rainbox-dev.github.io/DuAEF_Duik/contributing-guide
    - License: https://rainbox-dev.github.io/DuAEF_Duik/license
    - Credits: https://rainbox-dev.github.io/DuAEF_Duik/credits
    - Contact: https://rainbox-dev.github.io/DuAEF_Duik/contact
    - Donate: https://rainbox-dev.github.io/DuAEF_Duik/donation
